{% set name = "omero-py" %}
{% set version = "5.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e75f53cd59a37db2f58699114a9c8306361732f27d392e5f25dcf267f583e8e7

build:
  noarch: python
  number: 1
  script_env:
    - VERSION_SUFFIX

outputs:
  - name: omero-py-minimal
    build:
      noarch: python
      script: "python -m pip install . --no-deps --ignore-installed -vv "
    files:
      - '*'
    requirements:
      host:
        - pip
        - python =3
      run:
        - future
        - python =3
        - zeroc-ice36-python
    test:
      commands:
        - omero --help
        - omero version
      imports:
        - omero
        - omero.api
        - omero.clients
        - omero.cmd
        - omero.constants
        - omero.fs
        - omero.gateway
        - omero.grid
        - omero.install
        - omero.metadatastore
        - omero.model
        - omero.plugins
        - omero.romio
        - omero.sys
        - omero.util
        - omero_ext
  - name: omero-py
    build:
      noarch: python
    requirements:
      host:
        - python =3
        - pip
      run:
        - {{ pin_subpackage('omero-py-minimal', exact=True) }}
        - numpy
        - pillow

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Python bindings to the OMERO.blitz server
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-py

extra:
  recipe-maintainers:
    - ome
